# Generated by Django 3.2 on 2022-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='campus_id',
            field=models.IntegerField(null=True, verbose_name='ID Кампуса'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='users',
            name='school_login',
            field=models.CharField(max_length=100, null=True, verbose_name='Логин в школе'),
        ),
    ]
