# Generated by Django 3.2 on 2022-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0002_auto_20220816_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кампус',
                'verbose_name_plural': 'Кампусы',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Fullname в Telegram'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(choices=[('1', 'Гость'), ('2', 'Абитуриент'), ('3', 'Студент'), ('4', 'Саппорт'), ('5', 'Админушка')], default='1', max_length=1, verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('object_type', models.CharField(max_length=100, null=True, verbose_name='Тип')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Описание')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='Username в Telegram')),
                ('floor', models.IntegerField(null=True, verbose_name="Этаж'")),
                ('room_number', models.IntegerField(unique=True, verbose_name='Номер комнаты')),
                ('campus_id', models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.campuses', verbose_name='ID Кампуса')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, null=True, verbose_name='Статус')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Время начала')),
                ('fin_time', models.DateTimeField(null=True, verbose_name='Время окончания')),
                ('object_id', models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.objects', verbose_name='ID объекта')),
                ('user_id', models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.users', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирований',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='campus_id',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.campuses', verbose_name='ID Кампуса'),
        ),
    ]
