# Generated by Django 3.2 on 2022-08-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0003_auto_20220816_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.BooleanField(default=True, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(choices=[('1', 'Гость'), ('2', 'Абитуриент'), ('3', 'Студент'), ('4', 'Саппорт'), ('5', 'Админушка')], default='1', max_length=3, verbose_name='Группа'),
        ),
    ]
