# Generated by Django 3.2 on 2022-08-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0006_alter_users_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(choices=[('1', 'Гость'), ('2', 'Абитуриент'), ('3', 'Студент'), ('4', 'Саппорт'), ('5', 'Админушка')], max_length=3, verbose_name='Группа'),
        ),
    ]
