# Generated by Django 3.2 on 2022-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0010_auto_20220816_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='image',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Картинка'),
        ),
    ]
