# Generated by Django 3.2 on 2022-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0011_alter_objects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='floor',
            field=models.IntegerField(verbose_name="Этаж'"),
        ),
    ]
