# Generated by Django 3.2 on 2022-08-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0012_alter_objects_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='floor',
            field=models.IntegerField(null=True, verbose_name="Этаж'"),
        ),
        migrations.AlterField(
            model_name='objects',
            name='room_number',
            field=models.IntegerField(null=True, verbose_name='Номер комнаты'),
        ),
    ]
