# Generated by Django 3.2 on 2022-08-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0013_auto_20220817_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.campuses', verbose_name='ID Кампуса'),
        ),
    ]
