# Generated by Django 3.2 on 2022-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0014_bookings_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('1', 'Занят'), ('2', 'Свободен'), ('3', 'Недоступен')], default='1', max_length=3, null=True, verbose_name='Статус'),
        ),
    ]
