# Generated by Django 3.2 on 2022-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0015_alter_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.users', verbose_name='Школьный ник'),
        ),
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название типа объекта')),
                ('campus', models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.campuses', verbose_name='ID Кампуса')),
            ],
            options={
                'verbose_name': 'Тип Объекта',
                'verbose_name_plural': 'Типы объекта',
            },
        ),
        migrations.AlterField(
            model_name='objects',
            name='object_type',
            field=models.ForeignKey(max_length=100, null=True, on_delete=models.SET(0), to='adminka.objecttypes', verbose_name='Тип'),
        ),
    ]
