# Generated by Django 3.2 on 2022-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0016_auto_20220817_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), to='adminka.users', verbose_name='ID пользователя'),
        ),
    ]
