version: "3.3"


services:


  db:
    container_name: school_db
    image: postgres
    environment:
      POSTGRES_DB: "school"
      POSTGRES_USER: "school"
      POSTGRES_PASSWORD: "school"
    ports:
      - "5333:5432"
    networks:
      - botnet
    volumes:
      - ./pgdata:/var/lib/postgresql

  web:
    container_name: web
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - botnet
    depends_on:
      - db
    restart: always
    volumes:
      - .:/web_django
    ports:
      - "8888:8000"

  school:
    container_name: school_bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - .env
    depends_on:
      - web
    volumes:
    - .:/src

networks:
  botnet:
    driver: bridge